AWSTemplateFormatVersion: "2010-09-09"
Description: "Cafe S3 Template"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
